export const ADD_ACTIVITY_STARTED = "ADD_ACTIVITY_STARTED";
export const ADD_ACTIVITY_SUCCESS = "ADD_ACTIVITIY_SUCCESS";
export const ADD_ACTIVITY_FAIL = "ADD_ACTIVITY_FAIL";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const REQUEST_ACTIVITIES = "REQUEST_ACTIVITIES";
export const RECEIVE_ACTIVITIES = "RECEIVE_ACTIVITIES";

export const ADD_GOAL_STARTED = "ADD_GOAL_STARTED";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FAIL = "ADD_GOAL_FAIL";
export const DELETE_GOAL = "DELETE_GOAL";
export const EDIT_GOAL = "EDIT_GOAL";
export const UPDATE_GOALS = "UPDATE_GOALS";
export const REQUEST_GOALS = "REQUEST_GOALS";
export const RECEIVE_GOALS = "RECEIVE_GOALS";

export const TOGGLE_ADD_ACTIVITY_MODAL = "TOGGLE_ADD_ACTIVITY_MODAL";
export const TOGGLE_EDIT_ACTIVITY_MODAL = "TOGGLE_EDIT_ACTIVITY_MODAL";
export const TOGGLE_ADD_GOAL_MODAL = "TOGGLE_ADD_GOAL_MODAL";
export const TOGGLE_WELCOME_MODAL = "TOGGLE_WELCOME_MODAL";
export const TOGGLE_EDIT_GOAL_MODAL = "TOGGLE_EDIT_GOAL_MODAL";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
