// Activity-related action
export const ADD_ACTIVITY_STARTED = "ADD_ACTIVITY_STARTED";
export const ADD_ACTIVITY_SUCCESS = "ADD_ACTIVITIY_SUCCESS";
export const ADD_ACTIVITY_FAIL = "ADD_ACTIVITY_FAIL";

export const DELETE_ACTIVITY_STARTED = "DELETE_ACTIVITY_STARTED";
export const DELETE_ACTIVITY_SUCCESS = "DELETE_ACTIVITY_SUCCESS";
export const DELETE_ACTIVITY_FAIL = "DELETE_ACTIVITY_FAIL";

export const FETCH_ACTIVITIES_STARTED = "FETCH_ACTIVITIES_STARTED";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_FAIL = "FETCH_ACTIVITIES_FAIL";

// Goal-related action
export const ADD_GOAL_STARTED = "ADD_GOAL_STARTED";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FAIL = "ADD_GOAL_FAIL";

export const DELETE_GOAL_STARTED = "DELETE_GOAL_STARTED";
export const DELETE_GOAL_SUCCESS = "DELETE_GOAL_SUCCESS";
export const DELETE_GOAL_FAIL = "DELETE_GOAL_FAIL";

export const EDIT_GOAL_STARTED = "EDIT_GOAL_STARTED";
export const EDIT_GOAL_SUCCESS = "EDIT_GOAL_SUCCESS";
export const EDIT_GOAL_FAIL = "EDIT_GOAL_FAIL";

export const FETCH_GOALS_STARTED = "FETCH_GOALS_STARTED";
export const FETCH_GOALS_SUCCESS = "FETCH_GOALS_SUCCESS";
export const FETCH_GOALS_FAIL = "FETCH_GOALS_FAIL";

// UI-related action
export const TOGGLE_ADD_ACTIVITY_MODAL = "TOGGLE_ADD_ACTIVITY_MODAL";
export const TOGGLE_EDIT_ACTIVITY_MODAL = "TOGGLE_EDIT_ACTIVITY_MODAL";
export const TOGGLE_ADD_GOAL_MODAL = "TOGGLE_ADD_GOAL_MODAL";
export const TOGGLE_WELCOME_MODAL = "TOGGLE_WELCOME_MODAL";
export const TOGGLE_EDIT_GOAL_MODAL = "TOGGLE_EDIT_GOAL_MODAL";

// User-related actions
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
