export const ADD_GOAL = "ADD_GOAL";
export const DELETE_GOAL = "DELETE_GOAL";
export const UPDATE_GOALS = "UPDATE_GOALS";
export const FETCH_GOALS = "FETCH_GOALS";

export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const REQUEST_ACTIVITIES = "REQUEST_ACTIVITIES";
export const RECEIVE_ACTIVITIES = "RECEIVE_ACTIVITIES";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";

export const TOGGLE_ADD_ACTIVITY_MODAL = "TOGGLE_ADD_ACTIVITY_MODAL";
export const TOGGLE_ADD_GOAL_MODAL = "TOGGLE_ADD_GOAL_MODAL";
